name: Pinterest Daily Cron

on:
  schedule:
    - cron: "0 15 * * *"   # 8:30 PM IST (15:00 UTC)
  workflow_dispatch:       # allow manual run also

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ðŸ‘‡ Get today's date (YYYY-MM-DD)
      - name: Get Today Date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Run script
        run: |
          echo "Today's date: $TODAY_DATE"
          python cron_job.py
        env:
          TODAY_DATE: ${{ steps.date.outputs.today }}
          PINTEREST_REFRESH_TOKEN: ${{ secrets.PINTEREST_REFRESH_TOKEN }}
          PINTEREST_APP_ID: ${{ secrets.PINTEREST_APP_ID }}
          PINTEREST_APP_SECRET: ${{ secrets.PINTEREST_APP_SECRET }}
          PINTEREST_BOARD_ID: ${{ secrets.PINTEREST_BOARD_ID }}
          DRIVE_FOLDER_ID_1: ${{ secrets.DRIVE_FOLDER_ID_1 }}
          DRIVE_FOLDER_ID_2: ${{ secrets.DRIVE_FOLDER_ID_2 }}
          DRIVE_FOLDER_ID_3: ${{ secrets.DRIVE_FOLDER_ID_3 }}
          MAX_PINS_PER_DAY: ${{ secrets.MAX_PINS_PER_DAY }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
