name: Pinterest Daily Cron

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get Today Date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Run script
        run: python cron_job.py
        env:
          TODAY_DATE: ${{ steps.date.outputs.today }}
          PINTEREST_REFRESH_TOKEN: ${{ secrets.PINTEREST_REFRESH_TOKEN }}
          PINTEREST_APP_ID: ${{ secrets.PINTEREST_APP_ID }}
          PINTEREST_APP_SECRET: ${{ secrets.PINTEREST_APP_SECRET }}
          PINTEREST_BOARD_ID: ${{ secrets.PINTEREST_BOARD_ID }}
          DRIVE_FOLDER_ID_1: ${{ secrets.DRIVE_FOLDER_ID_1 }}
          DRIVE_FOLDER_ID_2: ${{ secrets.DRIVE_FOLDER_ID_2 }}
          DRIVE_FOLDER_ID_3: ${{ secrets.DRIVE_FOLDER_ID_3 }}
          MAX_PINS_PER_DAY: ${{ secrets.MAX_PINS_PER_DAY }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          TIMEZONE: ${{ secrets.TIMEZONE }}

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add uploaded_files.json
          git commit -m "Update uploaded files list for ${{ steps.date.outputs.today }}" || echo "No changes to commit"
          git push
